CREATE EXTENSION IF NOT EXISTS postgis;

-- 1) Keep old tables as backup and source for migration
ALTER TABLE IF EXISTS chat RENAME TO chat_legacy;
ALTER TABLE IF EXISTS decyzja RENAME TO decision_legacy;
ALTER TABLE IF EXISTS firma RENAME TO company_legacy;
ALTER TABLE IF EXISTS kategoria RENAME TO category_legacy;
ALTER TABLE IF EXISTS kategoria_skarga RENAME TO report_category_legacy;
ALTER TABLE IF EXISTS kategoria_lokalizacji RENAME TO location_category_legacy;
ALTER TABLE IF EXISTS kategoria_wydarzenie RENAME TO category_event_legacy;
ALTER TABLE IF EXISTS komentarz RENAME TO comment_legacy;
ALTER TABLE IF EXISTS lista_upodobanych RENAME TO user_list_legacy;
ALTER TABLE IF EXISTS lokalizacja RENAME TO location_legacy;
ALTER TABLE IF EXISTS moderator RENAME TO moderator_legacy;
ALTER TABLE IF EXISTS obserwowanie RENAME TO follow_legacy;
ALTER TABLE IF EXISTS ocena RENAME TO rating_legacy;
ALTER TABLE IF EXISTS osoba RENAME TO person_legacy;
ALTER TABLE IF EXISTS powiadomienie RENAME TO message_legacy;
ALTER TABLE IF EXISTS promowanie RENAME TO advertising_legacy;
ALTER TABLE IF EXISTS repost RENAME TO repost_legacy;
ALTER TABLE IF EXISTS skarga RENAME TO report_legacy;
ALTER TABLE IF EXISTS uzytkownik RENAME TO user_legacy;
ALTER TABLE IF EXISTS uzytkownik_chat RENAME TO user_chat_legacy;
ALTER TABLE IF EXISTS wydarzenie RENAME TO event_legacy;
ALTER TABLE IF EXISTS zdjecie RENAME TO photo_legacy;

-- 2) Corrected schema
CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    surname varchar(20) NULL,
    email varchar(254) NOT NULL,
    phone varchar(15) NOT NULL,
    birthdate date NOT NULL,
    password_hash varchar(255) NOT NULL,
    username varchar(20) NOT NULL,
    page_description varchar(150) NOT NULL,
    CONSTRAINT v3_app_user_pk PRIMARY KEY (id),
    CONSTRAINT v3_app_user_email_uk UNIQUE (email),
    CONSTRAINT v3_app_user_phone_uk UNIQUE (phone)
);

CREATE TABLE location_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    CONSTRAINT v3_location_category_pk PRIMARY KEY (id)
);

CREATE TABLE location (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    category_id bigint NOT NULL,
    point geometry(Point, 4326) NULL,
    region geometry(Polygon, 4326) NULL,
    CONSTRAINT v3_location_pk PRIMARY KEY (id)
);

CREATE TABLE chat (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    CONSTRAINT v3_chat_pk PRIMARY KEY (id)
);

CREATE TABLE category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    CONSTRAINT v3_category_pk PRIMARY KEY (id)
);

CREATE TABLE event (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(30) NOT NULL,
    description varchar(500) NOT NULL,
    location_id bigint NOT NULL,
    start_at timestamptz NOT NULL,
    end_at timestamptz NULL,
    created_at timestamptz NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_event_pk PRIMARY KEY (id),
    CONSTRAINT v3_event_end_after_start_ck CHECK (end_at IS NULL OR end_at >= start_at)
);

CREATE TABLE user_list (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_user_list_pk PRIMARY KEY (id)
);

CREATE TABLE report_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_type varchar(30) NOT NULL,
    CONSTRAINT v3_report_category_pk PRIMARY KEY (id)
);

CREATE TABLE moderator (
    user_id bigint NOT NULL,
    description varchar(200) NOT NULL,
    CONSTRAINT v3_moderator_pk PRIMARY KEY (user_id)
);

CREATE TABLE company (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(30) NOT NULL,
    link varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_company_pk PRIMARY KEY (id)
);

CREATE TABLE user_chat (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamptz NOT NULL,
    CONSTRAINT v3_user_chat_pk PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE report (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(100) NOT NULL,
    event_id bigint NOT NULL,
    category_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_report_pk PRIMARY KEY (id)
);

CREATE TABLE decision (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(100) NOT NULL,
    blocked_until timestamptz NOT NULL,
    moderator_id bigint NOT NULL,
    report_id bigint NOT NULL,
    CONSTRAINT v3_decision_pk PRIMARY KEY (id)
);

CREATE TABLE comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(100) NOT NULL,
    event_id bigint NOT NULL,
    parent_comment_id bigint NULL,
    comment_at timestamptz NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_comment_pk PRIMARY KEY (id)
);

CREATE TABLE photo (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_path varchar(255) NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT v3_photo_pk PRIMARY KEY (id)
);

CREATE TABLE category_event (
    category_id bigint NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT v3_category_event_pk PRIMARY KEY (category_id, event_id)
);

CREATE TABLE event_list (
    favourite_list_id bigint NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT v3_event_list_pk PRIMARY KEY (favourite_list_id, event_id)
);

CREATE TABLE follow (
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL,
    CONSTRAINT v3_follow_pk PRIMARY KEY (follower_id, following_id),
    CONSTRAINT v3_follow_no_self_ck CHECK (follower_id <> following_id)
);

CREATE TABLE rating (
    rating decimal(2,1) NOT NULL,
    event_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_rating_pk PRIMARY KEY (event_id, user_id),
    CONSTRAINT v3_rating_range_ck CHECK (rating BETWEEN 0 AND 5)
);

CREATE TABLE repost (
    event_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_repost_pk PRIMARY KEY (event_id, user_id)
);

CREATE TABLE advertising (
    start_date timestamptz NOT NULL,
    end_date timestamptz NOT NULL,
    event_id bigint NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT v3_advertising_pk PRIMARY KEY (event_id, company_id),
    CONSTRAINT v3_advertising_dates_ck CHECK (end_date >= start_date)
);

CREATE TABLE message (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text text NOT NULL,
    sent_at timestamptz NOT NULL,
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT v3_message_pk PRIMARY KEY (id)
);

-- 3) Data migration
INSERT INTO app_user (id, name, surname, email, phone, birthdate, password_hash, username, page_description)
SELECT
    p.id,
    p.imie,
    p.nazwisko,
    p.email,
    p.telefon,
    p.data_urodzenia,
    COALESCE(NULLIF(u.haslo, ''), 'legacy-no-password'),
    LEFT(COALESCE(NULLIF(u.username, ''), 'legacy_user_' || p.id::text), 20),
    COALESCE(NULLIF(u.opis_strony, ''), '')
FROM person_legacy p
LEFT JOIN user_legacy u ON u.osoba_id = p.id;

-- Safety user for empty legacy datasets
INSERT INTO app_user (id, name, surname, email, phone, birthdate, password_hash, username, page_description)
SELECT 1, 'System', NULL, 'system@local.invalid', '+000000000000', DATE '1970-01-01', 'system', 'system', 'System user'
WHERE NOT EXISTS (SELECT 1 FROM app_user);

INSERT INTO location_category (id, name)
SELECT id, nazwa
FROM location_category_legacy;

INSERT INTO location (id, name, category_id, point, region)
SELECT
    l.id,
    LEFT('location-' || l.id::text, 20),
    l.kategoria_lokalizacji_id,
    l.loklizacja_punkt,
    l.loklizacja_obszar
FROM location_legacy l
JOIN location_category lc ON lc.id = l.kategoria_lokalizacji_id;

INSERT INTO chat (id, name)
SELECT id, nazwa
FROM chat_legacy;

INSERT INTO category (id, name)
SELECT id, nazwa
FROM category_legacy;

INSERT INTO event (id, name, description, location_id, start_at, end_at, created_at, user_id)
SELECT
    e.id,
    e.nazwa,
    e.opis,
    e.lokalizacja_id,
    e.kiedy,
    NULL,
    COALESCE(e.kiedy, now()),
    COALESCE((SELECT MIN(id) FROM app_user), 1)
FROM event_legacy e
JOIN location l ON l.id = e.lokalizacja_id;

INSERT INTO user_list (id, name, user_id)
SELECT ul.id, ul.nazwa, ul.uzytkownik_id
FROM user_list_legacy ul
JOIN app_user u ON u.id = ul.uzytkownik_id;

INSERT INTO report_category (id, report_type)
SELECT id, nazwa
FROM report_category_legacy;

INSERT INTO moderator (user_id, description)
SELECT
    m.osoba_id,
    LEFT('legacy login=' || m.login || ', decisions=' || m.iloszcz_decyzij::text, 200)
FROM moderator_legacy m
JOIN app_user u ON u.id = m.osoba_id;

INSERT INTO company (id, name, link, user_id)
SELECT c.id, c.nazwa, c.link, c.uzytkownik_id
FROM company_legacy c
JOIN app_user u ON u.id = c.uzytkownik_id;

INSERT INTO user_chat (chat_id, user_id, joined_at)
SELECT DISTINCT src.chat_id, src.user_id, now()
FROM (
    SELECT uc.chat_id, uc.uzytkownik_id1 AS user_id FROM user_chat_legacy uc
    UNION ALL
    SELECT uc.chat_id, uc.uzytkownik_id2 AS user_id FROM user_chat_legacy uc
) src
JOIN chat c ON c.id = src.chat_id
JOIN app_user u ON u.id = src.user_id
ON CONFLICT DO NOTHING;

INSERT INTO report (id, description, event_id, category_id, user_id)
SELECT
    r.id,
    r.opis,
    r.wydarzenie_id,
    r.kategoria_skarga_id,
    r.uzytkownik_id
FROM report_legacy r
JOIN event e ON e.id = r.wydarzenie_id
JOIN report_category rc ON rc.id = r.kategoria_skarga_id
JOIN app_user u ON u.id = r.uzytkownik_id;

INSERT INTO decision (id, description, blocked_until, moderator_id, report_id)
SELECT
    d.id,
    d.opis,
    d.blokowanie,
    d.moderator_osoba_id,
    d.skarga_id
FROM decision_legacy d
JOIN moderator m ON m.user_id = d.moderator_osoba_id
JOIN report r ON r.id = d.skarga_id;

INSERT INTO comment (id, text, event_id, parent_comment_id, comment_at, user_id)
SELECT
    c.id,
    c.text,
    c.wydarzenie_id,
    NULL,
    COALESCE(ev.kiedy, now()),
    c.uzytkownik_id
FROM comment_legacy c
LEFT JOIN event_legacy ev ON ev.id = c.wydarzenie_id
JOIN event e ON e.id = c.wydarzenie_id
JOIN app_user u ON u.id = c.uzytkownik_id;

UPDATE comment c
SET parent_comment_id = src.parent_id
FROM (
    SELECT
        cl.id AS comment_id,
        CASE WHEN cl.komentarz_id = cl.id THEN NULL ELSE cl.komentarz_id END AS parent_id
    FROM comment_legacy cl
) src
WHERE c.id = src.comment_id
  AND src.parent_id IS NOT NULL
  AND EXISTS (SELECT 1 FROM comment p WHERE p.id = src.parent_id);

INSERT INTO photo (id, image_path, event_id)
SELECT p.id, p.image_path, p.wydarzenie_id
FROM photo_legacy p
JOIN event e ON e.id = p.wydarzenie_id;

INSERT INTO category_event (category_id, event_id)
SELECT DISTINCT ce.kategoria_id, ce.wydarzenie_id
FROM category_event_legacy ce
JOIN category c ON c.id = ce.kategoria_id
JOIN event e ON e.id = ce.wydarzenie_id
ON CONFLICT DO NOTHING;

INSERT INTO event_list (favourite_list_id, event_id)
SELECT ul.id, ul.wydarzenie_id
FROM user_list_legacy ul
JOIN user_list l ON l.id = ul.id
JOIN event e ON e.id = ul.wydarzenie_id
ON CONFLICT DO NOTHING;

INSERT INTO follow (follower_id, following_id)
SELECT DISTINCT f.uzytkownik_id, f.uzytkownik_2_id
FROM follow_legacy f
JOIN app_user u1 ON u1.id = f.uzytkownik_id
JOIN app_user u2 ON u2.id = f.uzytkownik_2_id
WHERE f.uzytkownik_id <> f.uzytkownik_2_id
ON CONFLICT DO NOTHING;

INSERT INTO rating (rating, event_id, user_id)
SELECT DISTINCT ON (r.wydarzenie_id, r.uzytkownik_id)
    LEAST(GREATEST(r.ocena, 0), 5)::numeric(2,1),
    r.wydarzenie_id,
    r.uzytkownik_id
FROM rating_legacy r
JOIN event e ON e.id = r.wydarzenie_id
JOIN app_user u ON u.id = r.uzytkownik_id
ORDER BY r.wydarzenie_id, r.uzytkownik_id, r.id DESC;

INSERT INTO repost (event_id, user_id)
SELECT DISTINCT rp.wydarzenie_id, rp.uzytkownik_id
FROM repost_legacy rp
JOIN event e ON e.id = rp.wydarzenie_id
JOIN app_user u ON u.id = rp.uzytkownik_id
ON CONFLICT DO NOTHING;

INSERT INTO advertising (start_date, end_date, event_id, company_id)
SELECT
    MIN(a.data_poczatku),
    CASE
        WHEN MAX(a.data_konca) >= MIN(a.data_poczatku) THEN MAX(a.data_konca)
        ELSE MIN(a.data_poczatku)
    END,
    a.wydarzenie_id,
    a.firma_id
FROM advertising_legacy a
JOIN event e ON e.id = a.wydarzenie_id
JOIN company c ON c.id = a.firma_id
GROUP BY a.wydarzenie_id, a.firma_id;

INSERT INTO message (id, text, sent_at, chat_id, user_id)
SELECT
    m.id,
    m.text,
    m.data,
    uc.chat_id,
    uc.uzytkownik_id1
FROM message_legacy m
JOIN user_chat_legacy uc ON uc.id = m.uzytkownik_chat_id
JOIN user_chat uc_new ON uc_new.chat_id = uc.chat_id AND uc_new.user_id = uc.uzytkownik_id1;

-- 4) Foreign keys
ALTER TABLE location ADD CONSTRAINT location_category_fk
    FOREIGN KEY (category_id) REFERENCES location_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE event ADD CONSTRAINT event_location_fk
    FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE event ADD CONSTRAINT event_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE user_list ADD CONSTRAINT user_list_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE moderator ADD CONSTRAINT moderator_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE company ADD CONSTRAINT company_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE user_chat ADD CONSTRAINT user_chat_chat_fk
    FOREIGN KEY (chat_id) REFERENCES chat (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE user_chat ADD CONSTRAINT user_chat_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE report ADD CONSTRAINT report_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE report ADD CONSTRAINT report_category_fk
    FOREIGN KEY (category_id) REFERENCES report_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE report ADD CONSTRAINT report_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE decision ADD CONSTRAINT decision_moderator_fk
    FOREIGN KEY (moderator_id) REFERENCES moderator (user_id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE decision ADD CONSTRAINT decision_report_fk
    FOREIGN KEY (report_id) REFERENCES report (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE comment ADD CONSTRAINT comment_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE comment ADD CONSTRAINT comment_parent_fk
    FOREIGN KEY (parent_comment_id) REFERENCES comment (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE comment ADD CONSTRAINT comment_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE photo ADD CONSTRAINT photo_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE category_event ADD CONSTRAINT category_event_category_fk
    FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE category_event ADD CONSTRAINT category_event_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE event_list ADD CONSTRAINT event_list_user_list_fk
    FOREIGN KEY (favourite_list_id) REFERENCES user_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE event_list ADD CONSTRAINT event_list_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE follow ADD CONSTRAINT follow_follower_fk
    FOREIGN KEY (follower_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE follow ADD CONSTRAINT follow_following_fk
    FOREIGN KEY (following_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE rating ADD CONSTRAINT rating_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE rating ADD CONSTRAINT rating_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE repost ADD CONSTRAINT repost_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE repost ADD CONSTRAINT repost_user_fk
    FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE advertising ADD CONSTRAINT advertising_event_fk
    FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE advertising ADD CONSTRAINT advertising_company_fk
    FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE message ADD CONSTRAINT message_user_chat_fk
    FOREIGN KEY (chat_id, user_id) REFERENCES user_chat (chat_id, user_id) NOT DEFERRABLE INITIALLY IMMEDIATE;

-- 5) FK indexes
CREATE INDEX IF NOT EXISTS idx_location_category_id ON location (category_id);
CREATE INDEX IF NOT EXISTS idx_event_location_id ON event (location_id);
CREATE INDEX IF NOT EXISTS idx_event_user_id ON event (user_id);
CREATE INDEX IF NOT EXISTS idx_user_list_user_id ON user_list (user_id);
CREATE INDEX IF NOT EXISTS idx_company_user_id ON company (user_id);
CREATE INDEX IF NOT EXISTS idx_user_chat_user_id ON user_chat (user_id);
CREATE INDEX IF NOT EXISTS idx_report_event_id ON report (event_id);
CREATE INDEX IF NOT EXISTS idx_report_category_id ON report (category_id);
CREATE INDEX IF NOT EXISTS idx_report_user_id ON report (user_id);
CREATE INDEX IF NOT EXISTS idx_decision_moderator_id ON decision (moderator_id);
CREATE INDEX IF NOT EXISTS idx_decision_report_id ON decision (report_id);
CREATE INDEX IF NOT EXISTS idx_comment_event_id ON comment (event_id);
CREATE INDEX IF NOT EXISTS idx_comment_parent_comment_id ON comment (parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_user_id ON comment (user_id);
CREATE INDEX IF NOT EXISTS idx_photo_event_id ON photo (event_id);
CREATE INDEX IF NOT EXISTS idx_category_event_event_id ON category_event (event_id);
CREATE INDEX IF NOT EXISTS idx_event_list_event_id ON event_list (event_id);
CREATE INDEX IF NOT EXISTS idx_follow_following_id ON follow (following_id);
CREATE INDEX IF NOT EXISTS idx_rating_user_id ON rating (user_id);
CREATE INDEX IF NOT EXISTS idx_repost_user_id ON repost (user_id);
CREATE INDEX IF NOT EXISTS idx_advertising_company_id ON advertising (company_id);
CREATE INDEX IF NOT EXISTS idx_message_chat_user_id ON message (chat_id, user_id);

-- 6) Align identity sequences with migrated IDs
DO $$
DECLARE
    seq_name text;
    max_id bigint;
    rec record;
BEGIN
    FOR rec IN
        SELECT * FROM (
            VALUES
                ('app_user', 'id'),
                ('location_category', 'id'),
                ('location', 'id'),
                ('chat', 'id'),
                ('category', 'id'),
                ('event', 'id'),
                ('user_list', 'id'),
                ('report_category', 'id'),
                ('company', 'id'),
                ('report', 'id'),
                ('decision', 'id'),
                ('comment', 'id'),
                ('photo', 'id'),
                ('message', 'id')
        ) AS t(table_name, column_name)
    LOOP
        seq_name := pg_get_serial_sequence(rec.table_name, rec.column_name);
        IF seq_name IS NOT NULL THEN
            EXECUTE format('SELECT COALESCE(MAX(%I), 1) FROM %I', rec.column_name, rec.table_name) INTO max_id;
            EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
        END IF;
    END LOOP;
END
$$;
